import re


with open('getCpuUsage.robot') as robot_file:
    robot_string = robot_file.read()
    
# print robot_string

match = re.compile('\*{3} Variables \*{3}')

for x in match.findall(robot_string):
    print x

print re.sub('\*{3} +Variables +\*{3}', '*** Variables ***\n${var1}  value1\n${var2}  value2 ', robot_string)
    
# *** Variables ***
# ${json_schema}  {"definitions":{},"$schema":"http://json-schema.org/draft-04/schema#","id":"http://ml-pa.com/m2cp.json","type":"object","properties":{"Type":{"id":"/properties/Type","type":"string","title":"The Type Schema.","description":"An explanation about the purpose of this instance.","default":""},"Name":{"id":"/properties/Name","type":"string","title":"The Name Schema.","description":"An explanation about the purpose of this instance.","default":""},"Data":{"id":"/properties/Data","type":"object","properties":{"ResponseValue":{"id":"/properties/Data/properties/ResponseValue","type":"object","properties":{"Levels":{"id":"/properties/Data/properties/ResponseValue/properties/Levels","type":"array","items":{"id":"/properties/Data/properties/ResponseValue/properties/Levels/items","type":"object","properties":{"standardLevel":{"id":"/properties/Data/properties/ResponseValue/properties/Levels/items/properties/standardLevel","type":"string","title":"The Standardlevel Schema.","description":"An explanation about the purpose of this instance.","default":""},"declaringClass":{"id":"/properties/Data/properties/ResponseValue/properties/Levels/items/properties/declaringClass","type":"string","title":"The Declaringclass Schema.","description":"An explanation about the purpose of this instance.","default":""}}}}}},"ResultType":{"id":"/properties/Data/properties/ResultType","type":"string","title":"The Resulttype Schema.","description":"An explanation about the purpose of this instance.","default":""}}},"Tag":{"id":"/properties/Tag","type":"string","title":"The Tag Schema.","description":"An explanation about the purpose of this instance.","default":""},"TimeStamp":{"id":"/properties/TimeStamp","type":"integer","title":"The Timestamp Schema.","description":"An explanation about the purpose of this instance.","default":0}}}
# ${data_payload_schema}  {"definitions":{},"$schema":"http://json-schema.org/draft-06/schema#","$id":"http://ml-pa.com/m2cp.json","type":"object","properties":{"Type":{"$id":"/properties/Type","type":"string","title":"The Type Schema","description":"An explanation about the purpose of this instance.","default":"","examples":["RESPONSE"]},"Name":{"$id":"/properties/Name","type":"string","title":"The Name Schema","description":"An explanation about the purpose of this instance.","default":"","examples":["getSupportStatus"]},"Data":{"$id":"/properties/Data","type":"object","properties":{"ResponseValue":{"$id":"/properties/Data/properties/ResponseValue","type":"object","properties":{"Message":{"$id":"/properties/Data/properties/ResponseValue/properties/Message","type":"string","title":"The Message Schema","description":"An explanation about the purpose of this instance.","default":"","examples":["No Support Console is Running"]},"TargetHost":{"$id":"/properties/Data/properties/ResponseValue/properties/TargetHost","type":"string","title":"The Targethost Schema","description":"An explanation about the purpose of this instance.","default":"","examples":[""]},"TargetPort":{"$id":"/properties/Data/properties/ResponseValue/properties/TargetPort","type":"integer","title":"The Targetport Schema","description":"An explanation about the purpose of this instance.","default":0,"examples":[0]}}},"ResultType":{"$id":"/properties/Data/properties/ResultType","type":"string","title":"The Resulttype Schema","description":"An explanation about the purpose of this instance.","default":"","examples":["SUCCESS"]}}},"Tag":{"$id":"/properties/Tag","type":"string","title":"The Tag Schema","description":"An explanation about the purpose of this instance.","default":"","examples":["11111111-1111-1111-1111-111111111111"]},"TimeStamp":{"$id":"/properties/TimeStamp","type":"integer","title":"The Timestamp Schema","description":"An explanation about the purpose of this instance.","default":0,"examples":[1515403263813]}}}
# ...